import 'package:ExpShop/fake_data/Colors.dart';
import 'package:ExpShop/models/categoryProduct.dart';
import 'package:ExpShop/models/product.dart';
import 'package:ExpShop/models/store.dart';
import 'package:ExpShop/models/user.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

final oCcy = new NumberFormat("#,##0", "en_US");

var listUser = [
  User(
    "Male",
      'Ng. Văn A',
      "Address1",
      "testShop@gmaiil.com",
      "username01",
      "01234566",
      "3HwkLw9H5rUp99tkSSW1",
      'assets/images/user.png',
    null
  ),

  User(
      "Male",
      'Ng. Văn A',
      "Address1",
      "test1@gmail.com",
      "username01",
      "01234566",
      "1",
      'assets/images/user.png',
      null
  ),
];

var listStore = [
  Store(
      shopColor: GREEN,
      storeID: 1,
      storeName: '7-eleven',
      address: '4 Trường Chinh, Phường 12, Tân Bình, Thành phố Hồ Chí Minh',
      description: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/shop1.jpg"),
  Store(
      shopColor: RED,
      storeID: 2,
      storeName: 'VinMart',
      address: '50 Tứ Hải, Phường 6, Tân Bình, Thành phố Hồ Chí Minh',
      description: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/shop2.jpg"),
  Store(
      shopColor: GREEN,
      storeID: 1,
      storeName: 'Family Mart',
      address:
          '590 Cách Mạng Tháng Tám, Phường 11, Quận 3, Thành phố Hồ Chí Minh',
      description: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/family.jpg"),
  Store(
      shopColor: RED,
      storeID: 2,
      storeName: 'Vinh Phúc',
      address: '319 Lý Thường Kiệt, Phường 15, Quận 11, Thành phố Hồ Chí Minh',
      description: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/vinhphuc.jpg"),
  Store(
      shopColor: RED,
      storeID: 2,
      storeName: 'Hà PHương',
      address: '16A Lê Hồng Phong, Phường 12, Quận 10, Thành phố Hồ Chí Minh',
      description: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/haphuong.png"),
];

var listCagory = [
  CategoryProduct(
      categoryID: 1,
      categoryName: "Bánh kẹo",
      urlImage: "assets/icons/candy.png"),
  CategoryProduct(
    categoryID: 2,
    categoryName: "Sữa",
    urlImage: "assets/icons/milk.png",
  ),
  CategoryProduct(
      categoryID: 4,
      categoryName: "Đồ ăn nhanh",
      urlImage: "assets/icons/noodles.png"),
  CategoryProduct(
      categoryID: 5,
      categoryName: "Ngủ cốc",
      urlImage: "assets/icons/walnut.png"),
  CategoryProduct(
      categoryID: 6,
      categoryName: "Đồ uống",
      urlImage: "assets/icons/soft-drink.png"),
  CategoryProduct(
      categoryID: 7,
      categoryName: "Đóng hộp",
      urlImage: "assets/icons/canned-food.png"),
  CategoryProduct(
      categoryID: 8,
      categoryName: "Gia vị",
      urlImage: "assets/icons/spices.png"),
  CategoryProduct(
      categoryID: 3, categoryName: "Khác", urlImage: "assets/icons/menu.png"),
];

var listProduct = [
  ProductItem(
      rating: 4.5,
      isRating: true,
      quantity: 15,
      km: '0.2km',
      productID: 1,
      productName: 'Hộp Bò Hầm',
      categoryID: 7,
      storeID: 2,
      price: 34000,
      like: 100,
      describe: '',
      promotionalPrice: 20000,
      image: 'assets/images/bohamhop.jpg'),
  ProductItem(
      rating: 3.5,
      isRating: true,
      quantity: 20,
      km: '0.8km',
      productID: 2,
      productName: 'Cá hộp',
      categoryID: 7,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/cahop.jpg'),
  ProductItem(
      rating: 3.5,
      isRating: false,
      quantity: 27,
      km: '0.3km',
      productID: 3,
      productName: 'CoCa Cola',
      categoryID: 6,
      storeID: 2,
      price: 14000,
      like: 100,
      describe: ' ',
      promotionalPrice: 7000,
      image: 'assets/images/cocacola.jpg'),
  ProductItem(
      rating: 4.2,
      isRating: true,
      quantity: 0,
      km: '0.7km',
      productID: 4,
      productName: 'Hạt Nêm Knorr',
      categoryID: 8,
      storeID: 2,
      price: 60000,
      like: 100,
      describe: '',
      promotionalPrice: 30000,
      image: 'assets/images/hatniemKnorr.jpg'),
  ProductItem(
      rating: 3.4,
      isRating: false,
      quantity: 0,
      km: '0.4km',
      productID: 5,
      productName: 'Mật Ong Xuân Nguyên',
      categoryID: 3,
      storeID: 2,
      price: 200000,
      like: 100,
      describe: 'c',
      promotionalPrice: 130000,
      image: 'assets/images/matong.jpg'),
  ProductItem(
      rating: 4.2,
      isRating: true,
      quantity: 32,
      km: '0.6km',
      productID: 6,
      productName: 'Ngũ cốc',
      categoryID: 5,
      storeID: 2,
      price: 50000,
      like: 100,
      describe: '',
      promotionalPrice: 26000,
      image: 'assets/images/ngucoc.jpg'),
  ProductItem(
      rating: 4.0,
      isRating: false,
      quantity: 45,
      km: '0.5km',
      productID: 7,
      productName: 'Pate Gan Ngỗng',
      categoryID: 7,
      storeID: 2,
      price: 45000,
      like: 100,
      describe: '',
      promotionalPrice: 30000,
      image: 'assets/images/pateganngong.jpg'),
  ProductItem(
      rating: 3.5,
      isRating: true,
      quantity: 14,
      km: '2.1km',
      productID: 7,
      productName: 'Nước giải khác Pepsi',
      categoryID: 6,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/pepsi.jpg'),
  ProductItem(
      rating: 5.0,
      isRating: false,
      quantity: 0,
      km: '2.8km',
      productID: 7,
      productName: 'Pho Mai Bò Cười',
      categoryID: 2,
      storeID: 2,
      price: 50000,
      like: 100,
      describe: '',
      promotionalPrice: 36000,
      image: 'assets/images/phomai.jpg'),
  ProductItem(
      rating: 4.2,
      isRating: true,
      quantity: 0,
      km: '2.2km',
      productID: 7,
      productName: 'Nước giải khát Sprite',
      categoryID: 6,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/sprite.jpg'),
  ProductItem(
      rating: 3.9,
      isRating: false,
      quantity: 10,
      km: '2.7km',
      productID: 7,
      productName: 'Sữa Chưa Vinamilk',
      categoryID: 2,
      storeID: 2,
      price: 25000,
      like: 100,
      describe: '',
      promotionalPrice: 17000,
      image: 'assets/images/suachuavinamilk.jpg'),
  ProductItem(
      rating: 4.4,
      isRating: true,
      quantity: 8,
      km: '2.5km',
      productID: 7,
      productName: 'Sữa Ông Thọ',
      categoryID: 2,
      storeID: 2,
      price: 24000,
      like: 100,
      describe: '',
      promotionalPrice: 17000,
      image: 'assets/images/suaongtho.jpg'),
  ProductItem(
      rating: 4.2,
      isRating: false,
      quantity: 0,
      km: '2.0km',
      productID: 7,
      productName: 'Sữa Tươi 100%',
      categoryID: 2,
      storeID: 2,
      price: 20000,
      like: 100,
      describe: '',
      promotionalPrice: 14000,
      image: 'assets/images/suatuoi.jpg'),
  ProductItem(
      rating: 3.4,
      isRating: true,
      quantity: 27,
      km: '2.6km',
      productID: 7,
      productName: 'Thịt hộp',
      categoryID: 7,
      storeID: 2,
      price: 55000,
      like: 100,
      describe: '',
      promotionalPrice: 36000,
      image: 'assets/images/thithop.jpg'),
  ProductItem(
      rating: 3.5,
      isRating: true,
      quantity: 0,
      km: '2.7km',
      productID: 7,
      productName: 'Yến Mạch',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      promotionalPrice: 67000,
      image: 'assets/images/suaongtho.jpg'),
  ProductItem(
      rating: 4.0,
      isRating: false,
      quantity: 33,
      km: '3km',
      productID: 7,
      productName: 'Bánh đậu xanh',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      color: Colors.black,
      promotionalPrice: 67000,
      image: 'assets/images/banhdauxanh.jpg'),
  ProductItem(
      rating: 3.7,
      isRating: true,
      quantity: 7,
      km: '2.5km',
      productID: 7,
      productName: 'Trà xanh cozy',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      color: Colors.green,
      promotionalPrice: 67000,
      image: 'assets/images/traxanh.jpg'),
];
