import 'package:ExpShop/fake_data/Colors.dart';
import 'package:ExpShop/models/categoryProduct.dart';
import 'package:ExpShop/models/product.dart';
import 'package:ExpShop/models/store.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

final oCcy = new NumberFormat("#,##0", "en_US");

var listStore = [
  Store(
      shopColors: GREEN,
      storeID: 1,
      storeName: '7-eleven',
      address: 'Quan 1 HCM',
      describe: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/shop1.jpg"),
  Store(
      shopColors: RED,
      storeID: 2,
      storeName: 'VinMart',
      address: 'Quan 1 HCM',
      describe: '',
      longitude: 0000,
      latitude: 0000,
      phoneNumber: "0123456789",
      urlImage: "assets/images/shop2.jpg"),
];

var listCagory = [
  CategoryProduct(
      categoryID: 1,
      categoryName: "Bánh kẹo",
      urlImage: "assets/icons/candy.png"),
  CategoryProduct(
    categoryID: 2,
    categoryName: "Sữa",
    urlImage: "assets/icons/milk.png",
  ),
  CategoryProduct(
      categoryID: 4,
      categoryName: "Đồ ăn nhanh",
      urlImage: "assets/icons/noodles.png"),
  CategoryProduct(
      categoryID: 5,
      categoryName: "Ngủ cốc",
      urlImage: "assets/icons/walnut.png"),
  CategoryProduct(
      categoryID: 6,
      categoryName: "Đồ uống",
      urlImage: "assets/icons/soft-drink.png"),
  CategoryProduct(
      categoryID: 7,
      categoryName: "Đóng hộp",
      urlImage: "assets/icons/canned-food.png"),
  CategoryProduct(
      categoryID: 8,
      categoryName: "Gia vị",
      urlImage: "assets/icons/spices.png"),
  CategoryProduct(
      categoryID: 3, categoryName: "Khác", urlImage: "assets/icons/menu.png"),
];

var listProduct = [
  ProductItem(
      productID: 1,
      productName: 'Hộp Bò Hầm',
      categoryID: 7,
      storeID: 2,
      price: 34000,
      like: 100,
      describe: '',
      promotionalPrice: 20000,
      image: 'assets/images/bohamhop.jpg'),
  ProductItem(
      productID: 2,
      productName: 'Cá hộp',
      categoryID: 7,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/cahop.jpg'),
  ProductItem(
      productID: 3,
      productName: 'CoCa Cola',
      categoryID: 6,
      storeID: 2,
      price: 14000,
      like: 100,
      describe: ' ',
      promotionalPrice: 7000,
      image: 'assets/images/cocacola.jpg'),
  ProductItem(
      productID: 4,
      productName: 'Hạt Nêm Knorr',
      categoryID: 8,
      storeID: 2,
      price: 60000,
      like: 100,
      describe: '',
      promotionalPrice: 30000,
      image: 'assets/images/hatniemKnorr.jpg'),
  ProductItem(
      productID: 5,
      productName: 'Mật Ong Xuân Nguyên',
      categoryID: 3,
      storeID: 2,
      price: 200000,
      like: 100,
      describe: 'c',
      promotionalPrice: 130000,
      image: 'assets/images/matong.jpg'),
  ProductItem(
      productID: 6,
      productName: 'Ngũ cốc',
      categoryID: 5,
      storeID: 2,
      price: 50000,
      like: 100,
      describe: '',
      promotionalPrice: 26000,
      image: 'assets/images/ngucoc.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Pate Gan Ngỗng',
      categoryID: 7,
      storeID: 2,
      price: 45000,
      like: 100,
      describe: '',
      promotionalPrice: 30000,
      image: 'assets/images/pateganngong.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Nước giải khác Pepsi',
      categoryID: 6,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/pepsi.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Pho Mai Bò Cười',
      categoryID: 2,
      storeID: 2,
      price: 50000,
      like: 100,
      describe: '',
      promotionalPrice: 36000,
      image: 'assets/images/phomai.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Nước giải khát Sprite',
      categoryID: 6,
      storeID: 2,
      price: 12000,
      like: 100,
      describe: '',
      promotionalPrice: 7000,
      image: 'assets/images/sprite.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Sữa Chưa Vinamilk',
      categoryID: 2,
      storeID: 2,
      price: 25000,
      like: 100,
      describe: '',
      promotionalPrice: 17000,
      image: 'assets/images/suachuavinamilk.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Sữa Ông Thọ',
      categoryID: 2,
      storeID: 2,
      price: 24000,
      like: 100,
      describe: '',
      promotionalPrice: 17000,
      image: 'assets/images/suaongtho.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Sữa Tươi 100%',
      categoryID: 2,
      storeID: 2,
      price: 20000,
      like: 100,
      describe: '',
      promotionalPrice: 14000,
      image: 'assets/images/suatuoi.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Thịt hộp',
      categoryID: 7,
      storeID: 2,
      price: 55000,
      like: 100,
      describe: '',
      promotionalPrice: 36000,
      image: 'assets/images/thithop.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Yến Mạch',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      promotionalPrice: 67000,
      image: 'assets/images/suaongtho.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Bánh đậu xanh',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      color: Colors.black,
      promotionalPrice: 67000,
      image: 'assets/images/banhdauxanh.jpg'),
  ProductItem(
      productID: 7,
      productName: 'Trà xanh cozy',
      categoryID: 5,
      storeID: 2,
      price: 100000,
      like: 100,
      describe: '',
      color: Colors.green,
      promotionalPrice: 67000,
      image: 'assets/images/traxanh.jpg'),
];
